host: localhost:9000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is simple API documentation for eFishery e-Commerce project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: eFishery e-Commerce API
  version: "1.0"
paths: {}
swagger: "2.0"
